In [2]:
import numpy as np

# Creating a 1D array from a list
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
# Creating a 2D array from a list of lists
b = np.array([[1, 2],
              [3, 4]])

print(b)

[[1 2]
 [3 4]]


In [4]:
# Creating a 3D array from a list of lists of lists
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])

b = np.array([[1, 1, 1],
              [1, 1, 2],
              [1, 1, 2]])


print(a + b)


[[2 1 1]
 [2 2 3]
 [3 1 2]]


In [6]:
print(a - b)

[[ 0 -1 -1]
 [ 0  0 -1]
 [ 1 -1 -2]]


In [7]:

print(a * b)

[[1 0 0]
 [1 1 2]
 [2 0 0]]


In [8]:

print(a / b)

[[1.  0.  0. ]
 [1.  1.  0.5]
 [2.  0.  0. ]]


In [9]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])

print(np.max(a))

2


In [10]:
print(np.min(a))

0


In [11]:
print(np.average(a))

0.6666666666666666


In [15]:
"""
How do we find the maximum after-tax income in a group of people,
given their yearly salary and tax rates?

Let’s tackle this problem by using the salary data of Alice, Bob, and Tim.
It seems like Bob has enjoyed the highest salary in the last three years.
But is he actually bringing home the most money, considering the individual tax rates
of our three friends?
"""

## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                     [0.4, 0.5, 0.5],
                     [0.1, 0.2, 0.1]])

max_income = np.max(salaries - salaries * taxation)
print(max_income)
print("")
print(salaries - salaries * taxation)

81.0

[[79.2  75.75 80.34]
 [66.   54.   52.5 ]
 [81.   70.4  76.5 ]]


In [18]:
lista_python = [[0.2, 0.25, 0.22],
                [0.4, 0.5, 0.5],
                [0.1, 0.2, 0.1]]

print(lista_python[0][1])

lista_numpy = np.array(lista_python)
print(lista_numpy[0,1]) #Easier

0.25
0.25


In [19]:
a = np.array([55, 56, 57, 58, 59, 60, 61])
print(a[:1:-2])

[61 59 57]


In [21]:
print(a[:2:-2])

[61 59]


In [49]:
print(a[:1:-2])
print(a[-1:1:-2])
print(a[-2:-3:-1])
print(a[-2:-4:-1])

[61 59 57]
[61 59 57]
[60]
[60 59]


In [54]:
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# Third col: [ 2  6 10 14]
print(a[:, 2])



[ 2  6 10 14]


In [55]:
# Second row: [4 5 6 7]
print(a[1, :])

[4 5 6 7]


In [57]:
# Second row, every other element: [4 6]
print(a[1, ::2])

[4 6]


In [58]:
# All columns except last:
print(a[:, :-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [59]:
a = np.array([1, 2, 3, 4])
print(a.ndim)

1


In [60]:
b = np.array([[2, 1, 2], [3, 2, 3], [4, 3, 4]])
print(b.ndim)

2


In [61]:
c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
              [[1, 2, 4], [2, 3, 5], [3, 4, 6]]])

print(c.ndim)
print(c.shape)

3


In [75]:
"""
You have data for a variety of professions, and you want to increase
the salaries of just the data scientists by 10 percent every other year.
"""

# Data: yearly salary in ($1000) [2025, 2026, 2027]
dataScientist =     [130, 132, 137]
productManager =    [127, 140, 145]
designer =          [118, 118, 127]
softwareEngineer =  [129, 131, 137]

employees = np.array([dataScientist,
                      productManager,
                      designer,
                      softwareEngineer])

employees[0,] = employees[0,]*1.1
employees

array([[143, 145, 150],
       [127, 140, 145],
       [118, 118, 127],
       [129, 131, 137]])

In [77]:
X = np.array([[1, 0, 0],
              [0, 2, 2],
              [3, 0, 0]])

print(np.nonzero(X))
print( X[0,0])
print( X[1,2])

(array([0, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))
1
